### ISSUE TITLE
Missing Button Information in dialog

### ISSUE THREAD

**Issue by LuxiWang99** [izgzhen/markii#27]
In "ui-reverse/tests/test01/", the buttons on the dialog: button1 and button2 (Yes and No buttons) are not included in idNames.facts. Nor are their onClick method shown in eventHandler.

**Comment by izgzhen** [comment]
Dialog has some built-in button sub-nodes

**Comment by izgzhen** [comment]
https://developer.android.com/guide/topics/ui/dialogs

**Comment by izgzhen** [comment]
Check where `containsView` is written

**Comment by izgzhen** [comment]
`nodeID` -- sequentially generated intege, `idName`/`id-name` -- android id-name, `button1`
