### ISSUE TITLE
DialogView is not analyzed by VASCO

### ISSUE THREAD

**Issue by LuxiWang99** [izgzhen/markii#49]
In test01, the dialog linked to the continue button is not analyzed, in which case its aftDomain is null.

**Comment by LuxiWang99** [comment]
[WARN] Null endpoint: <com.example.test01.MainActivity$1$2: void onClick(android.content.DialogInterface,int)>
[WARN] Null endpoint: <com.example.test01.Main2Activity$2: void onClick(android.content.DialogInterface,int)>
[WARN] Null endpoint: <com.example.test01.Main2Activity$1: void onClick(android.content.DialogInterface,int)>
[WARN] Null endpoint: <com.example.test01.MainActivity: boolean onCreateOptionsMenu(android.view.Menu)>
[WARN] Null endpoint: <com.example.test01.MainActivity$1$1: void onClick(android.content.DialogInterface,int)>

**Comment by izgzhen** [comment]
https://github.com/izgzhen/markii/issues/51 First, it is *not* true that DialogView itself are not analyzed. The above list contains only two types of views:

- Buttons of DialogView
- Menu View
